### ISSUE TITLE
Unused imports are not reported in 2.13.2

### ISSUE THREAD

**Issue by GuillaumeSaintRaymondSonos** [DavidGregory084/sbt-tpolecat#22] opened 2020-06-05 06:06 UTC
Works great with Scala `2.13.1`, tried with last version `0.1.12`.
Is this something known ?
I see that on the README, it's tested only with 2.13.1

**Comment by SethTisue** [comment] 2020-06-08 23:03
it appears from https://github.com/DavidGregory084/sbt-tpolecat/blob/master/src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala that the plugin does enable `-Wunused:imports`

Not sure, but perhaps it's something specific to your code (and perhaps ultimately there's a scalac bug involved). Attempting to isolate the problem would resolve the question one way or the other.

**Comment by GuillaumeSaintRaymondSonos** [comment] 2020-06-09 06:06
Thanks for the response, I managed to reproduce the problem with a simple project https://github.com/GuillaumeSaintRaymondSonos/sbt-tpolecat-circe/

By default, unused warning reporting is working well with Scala 2.13.2 but when I add circe dependency and after adding a `scalac` option for `@JsonCodec`. This is where the behaviour is different between 2.13.1/2.13.2

**Comment by SethTisue** [comment] 2020-06-09 13:46
sounds like not a problem in this repo, then. sounds to me like you should try circe issue tracker next, if the problem isn't reproducible without circe.

I wonder if it's related to https://github.com/scala/scala/pull/8799 . if you're really determined to track this down, one path forward would be to use `git bisect` or https://github.com/adriaanm/binfu/blob/master/bisect.sh to pinpoint the exact scala/scala PR when this regressed (and/or just browse all the merged 2.13.2 PRs yourself)

**Closed** 2020-06-09 13:57 UTC

**Comment by GuillaumeSaintRaymondSonos** [comment] 2020-06-29 08:57
Scala 2.13.3 fixed the issue !
